#!/bin/bash

functions_list='Hypersphere Hyperellipsoid Schwefel Ackley Michalewicz'
n_dims_values=(2 3 4 6 8 10 12 16)
total_samples_values=(25 50 100 200 400)
for bench_func in $functions_list; do
  for n_dims in "${n_dims_values[@]}"; do
    for total_samples in "${total_samples_values[@]}"; do
        sbatch --export=BENCH_FUNC=$bench_func,N_DIMS=$n_dims,TOTAL_SAMPLES=$total_samples job_scripts/mobed_ntrials_experiment
    done
  done
done
